language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
cache:
  directories:
    - node_modules
notifications:
  email:       false

script:
  - npm test
  - gulp
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
