language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
cache:
  directories:
    - node_modules
notifications:
  email:       false
script:
  - npm test
  - npm run build
deploy:
  provider: netlify
  site: gallant-bardeen-11c2e8
  auth: <encrypted auth>
  local_dir: "build/"
